name: Validate plugin.json

on:
  push:
    paths:
      - 'plugins.json'
  pull_request:
    paths:
      - 'plugins.json'
  workflow_dispatch: # 支持手动触发

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate plugins.json format
        run: |
          sudo apt-get install jq
          jq . plugins.json > /dev/null

      - name: Check repository URLs
        run: |
          # 提取 plugins.json 中的 repo 字段并检查可访问性
          repos=$(jq -r '.. | objects | .repo? // empty' plugins.json)
          for repo in $repos; do
            if curl --output /dev/null --silent --head --fail "$repo"; then
              echo "Repository $repo is accessible."
            else
              echo "Repository $repo is NOT accessible." && exit 1
            fi
          done

